# Generated by Django 2.0.4 on 2018-08-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_venta', models.CharField(choices=[('PO1', 'Opcion 1'), ('P02', 'Opcion 2')], default='PO1', max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de venta',
                'verbose_name_plural': 'Tipos de venta',
            },
        ),
    ]
