# Generated by Django 2.0.4 on 2019-05-16 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='facturaCompra',
            fields=[
                ('idFacturaCompra', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.Proveedor', verbose_name='Nombre del proveedor')),
            ],
            options={
                'verbose_name': 'Factura de compra',
                'verbose_name_plural': 'Facturas de compra',
            },
        ),
        migrations.CreateModel(
            name='facturaCompraContieneProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idFacturaCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura_de_compra.facturaCompra')),
                ('idProducto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.Producto', verbose_name='Nombre del producto')),
            ],
            options={
                'verbose_name': 'Factura de compra contiene productos',
                'verbose_name_plural': 'Facturas de compra contiene productos',
            },
        ),
    ]
